---

  - name: Download WAR to server
    copy: src=helloworld-1.0.0-BUILD-SNAPSHOT.war dest=/tmp
  
  - name: Unzip WAR file
    unarchive: src=/tmp/helloworld-1.0.0-BUILD-SNAPSHOT.war dest=/usr/share/tomcat/webapps/helloworld copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - restart tomcat
   
